from PyQt_recipe_editor_mainwindow import Ui_MainWindow
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QCompleter 
from ingredienttablewidget import IngredientsTableWidget

class RecipeEditorView(Ui_MainWindow):
    """ Recipe editor view 
    inherits from Ui_MainWindow generated by Qt Designer and implements custom Ingredient QTablewidget """

    database_model = {
        'recipe_titles': [],
        'tags': [],
        'ingredient_functions': [],
        'ingredient_categories': [],
        'ingredients': [],
        'recipe_types': []
    }

    def __init__(self, main_window):
        super().__init__()
        super().setupUi(main_window)

        #set dictionary for static offline database data

        self.inpIngredients = IngredientsTableWidget(self.centralwidget, self.database_model)
        self.inpIngredients.setGeometry(QtCore.QRect(20, 330, 691, 192)) 

    def enable_autocomplete(self):
        tag_completer = QCompleter(self.database_model['tags'])
        self.inpTag.setCompleter(tag_completer)
        recipe_name_completer = QCompleter(self.database_model['recipe_titles'])
        self.inpRecTitle.setCompleter(recipe_name_completer)


    def load_static_database_data(self):
        """ loads database data into view, for calling when database is ready 
        """
        
        db = self.database_model 
        self.inpRecType.addItems(db["recipe_types"])
        self.inpIngredients.initiate_rows(db)

    def load_manifest_in_assistant(self):
        try:
            with open('database_manifest.md') as f:
                manifest = f.read()
        except FileNotFoundError: 
            manifest = 'ERROR: Manifest file not found'
        enriched_manifest = self._enrich_manifest(manifest)
        self.disAssistantHUD.setMarkdown(enriched_manifest)

    def _enrich_manifest(self, manifest):        
        #seed text 
        enriched_manifest = manifest

        # Recipes 
        recipe_header_text =  '\n ## Opskrifter \n'
        db_recipe_titles_joined = ', '.join(self.database_model['recipe_titles'])
        enriching_text = recipe_header_text + db_recipe_titles_joined + '\n\n'
        enriched_manifest += enriching_text
        
        # Tags 
        tag_header_text = '\n ## Tags \n'
        db_tags_joined = ', '.join(self.database_model['tags']) 
        enriching_text = tag_header_text + db_tags_joined
        enriched_manifest += enriching_text
        return enriched_manifest

    
    def read_ingredients(self):
        """ returns ingredients (list): list of ingredients added in the view """
        ingredients = self.inpIngredients.get_ingredients()
        return ingredients
        
    # og saa videre.... her skal vaere kode til at samle QTableWidget og definere metoder som controlleren skal kunne kalde 

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = RecipeEditorView(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())